---
title: "9 Apri 2021 class"
author: "Brian P Steves"
date: "4/9/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)


```


```{r}
a <- c(1,2,3,4)
a
str(a)
c(1:4)

c("John","Tom","Bob")

c(TRUE, FALSE, T, F)
```
```{r}

a <- c(1:4)
a = c(1:4)
c(1:4) -> a
b <- 4
b == 4
b == 3
```
```{r}
matrix(1:100, nrow=10)
matrix(1:13, nrow=4)
l <- c("a","b","c")
n <- c(1:3)
matrix(l,n)
```
```{r}
data.frame(l, n)
tibble(l,n)
```
```{r}
a <- data.frame(l,n)
a
b <- as_tibble(a)
b
c<- as.matrix(a)
c
```
```{r}
b <- list(c, b, a, l, n)
b
```
## Data importing
```{r}

#RData
load("mydatafilename.Rdata")

#csv
dat <- read.csv("data/wk1spdat.csv")
dat2 <- read_csv("data/wk1spdat.csv")

bike_dat <- read_csv("https://s3.amazonaws.com/biketown-tripdata-public/2016_07.csv")
```
```{r}
excel_dat <- "Bay	Species	Year
Chesapeake Bay	Botrylloides violaceus	2000
Chesapeake Bay	Diplosoma listerianum	2001
Chesapeake Bay	Styela canopus	2000
Chesapeake Bay	Styela plicata	2002
San Francisco Bay	Ascidia zara	2000
San Francisco Bay	Botrylloides diegensis	1983
San Francisco Bay	Botrylloides violaceus	1973
San Francisco Bay	Botryllus schlosseri	1947
San Francisco Bay	Ciona robusta	1932
San Francisco Bay	Ciona savignyi	1993
San Francisco Bay	Corella inflata	2008
San Francisco Bay	Didemnum vexillum	1993
San Francisco Bay	Diplosoma listerianum	1948
San Francisco Bay	Microcosmus squamiger	2016
San Francisco Bay	Molgula ficus	2005
San Francisco Bay	Molgula manhattensis	1955
San Francisco Bay	Polyandrocarpa zorritensis	2001
"
```

```{r}
write.csv(sel_taxa, "data/sel_taxa.csv")
write_csv(sel_taxa, "data/sel_taxa.csv")

library(readr)
wk1samples <- read_csv("data/wk1samples.csv")
View(wk1samples)

```


```{r}
library(readxl)

tuni_dat_excel <- read_excel("data/sf_cb_tb_tunicates.xlsx", 1)


```



```{r}
library(lubridate)

mydate <- "4/21/2021"
as.Date(mydate, "%d/%M/%Y")

mydate2 <- "September 5, 2021"
a <-mdy(mydate)

mdy(mydate2)

dates <- c("4/21/2021", "Apr 3, 2020")
mdy(dates)

```

```{r}
library(stringr)


```


