ESM 505/ESR 605 : Data Management, Spring 2016

Module 12: Version Control with Git 
====================

## Git

Git is a distributed revision control system used for source code management.  It allows mulitple users to work on the same project and to track all changes through time.  Even if you use Git all my yourself, the ability to go back, view and then roll back to earlier versions of code is very useful if you ever end up on a programming wild goose chase.

I don't have a module *per se* for this topic.  Rather, I'll point you to these links and then do a demonstration in class on Monday.

https://www.rstudio.com/ide/docs/version_control/overview

http://www.molecularecologist.com/2013/11/using-github-with-r-and-rstudio/

http://nyuccl.org/pages/GitTutorial/


## Github

Github is a hosting site for GIT based programming repositories.  Think of it as an advanced Dropbox type site.   GitHub adds a few features to your Git repository..

1. Easy access your repository from the web
2. Viewing your files (scritps, markdown, data frames, images, pdfs) directly
3. Issue tracker
4. History viewer (view multiple versions of a file at once)

There are two basic options.. 

1. Free if you leave your repositories public
2. Pay monthly fee if you want your repositories private


I'm cheap, so I just leave my repositories open to the public, but I make sure that no sensitive data or information about passwords can be found in the repositories.

In fact, I've written all the code for these modules using R Markdown and all of my Rmd files can be found in the following github repository.

https://github.com/bsteves/DataManagementClass


#BitBucket

BitBucket is an alternative to GitHub.  However, it allows for free private repositories as long as you don't want to share them with a lot of people.

## Homework

I highly recommend everyone sign up for a free GitHub or BitBucket account.

https://github.com/
https://bitbucket.com/

If you are comfortable enough with git and github it would be an ideal place to host your final report files.



